CREATE TABLE User(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(22) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL 
);

CREATE TABLE Category(
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(225) NOT NULL
     );


CREATE TABLE Todo(  
    id BIGINT AUTO_INCREMENT PRIMARY KEY, 
    title VARCHAR(255) NOT NULL, 
    description TEXT NOT NULL,  
    done BOOLEAN DEFAULT FALSE, 
    due_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP 
    user_id BIGINT,
    category_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES User(id),
    FOREIGN KEY (category_id) REFERENCES Category(id)
);

CREATE TABLE Tag(
    name VARCHAR(225) NOT NULL,
    user_id BIGIN AUTO_INCREMENTT,
    FOREIGN KEY (user_id) REFERENCES User(id),
    PRIMARY KEY (name , user_id)
);
